# wrangler.toml

name = "contact-forms"
workers_dev = true
compatibility_date = "2024-07-24"
main = "src/index.js"
node_compat = true

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Routing
routes = [
  { pattern = "*.civiclabs.us/api/contact", zone_name = "civiclabs.us" }
]

# Email binding
send_email = [
  { type = "send_email", name = "SEB" }
]

# Vars
[vars]
  FROM_EMAIL = "${FROM_EMAIL}"
  DESTINATION_EMAIL = "${DESTINATION_EMAIL}"
  SLACK_WEBHOOK = "$SLACK_WEBHOOK"
  DESTINATION_CA_EMAIL = "$DESTINATION_CA_EMAIL"
  DESTINATION_HL_EMAIL = "$DESTINATION_HL_EMAIL"
