name: ☁️ Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ☁️👷
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Manage Secrets
        run: |
          sed -i 's/\${CLOUDFLARE_ACCOUNT_ID}/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/g' wrangler.toml
          sed -i 's/\${DESTINATION_EMAIL}/${{ secrets.DESTINATION_EMAIL }}/g' wrangler.toml
          sed -i 's/\${FROM_EMAIL}/${{ secrets.FROM_EMAIL }}/g' wrangler.toml
          sed -i 's/\${SLACK_WEBHOOK}/${{ secrets.SLACK_WEBHOOK }}/g' wrangler.toml
          sed -i 's/\${DESTINATION_CA_EMAIL}/${{ secrets.DESTINATION_CA_EMAIL }}/g' wrangler.toml
          sed -i 's/\${DESTINATION_HL_EMAIL}/${{ secrets.DESTINATION_HL_EMAIL }}/g' wrangler.toml

      - name: Debug Wrangler.toml
        run: cat wrangler.toml # Add this line to check the wrangler.toml file

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
